"""The cross-genre pair script must not silently produce nothing.

Under real order-2 signatures the corpus-wide mean pairwise similarity is
approximately 0.023, so the script's default ``--min-similarity 0.7``
threshold selects no cross-genre pairs at all. The original control flow
logged a warning and ``return``ed, so the process exited 0 having written no
figure. A pipeline step that is wired in, exits successfully, and produces no
output is indistinguishable from one that worked -- which is how
``cross_genre_similarity.png`` came to be cited by the dissertation while
never actually being generated by the canonical run.

The script must instead fail loudly so the pipeline surfaces the condition.
"""

from __future__ import annotations

import inspect

from src.scripts import find_cross_genre_similar_songs as cross_genre_module


def test_empty_pair_set_does_not_exit_successfully():
    """No-pairs must raise, not `return`, so the exit code is non-zero."""
    source = inspect.getsource(cross_genre_module.main)
    marker = "if not pairs:"
    assert marker in source, "expected an explicit empty-pairs branch"
    branch = source[source.index(marker) :]
    # The branch must terminate the process abnormally rather than returning.
    branch_head = branch[: branch.index("# Create visualisation")]
    assert "return" not in branch_head, (
        "empty-pairs branch still returns silently; it must raise so the "
        "pipeline cannot record a successful step that produced no figure"
    )
    assert (
        "raise" in branch_head or "sys.exit" in branch_head
    ), "empty-pairs branch must raise or exit non-zero"
